config/routes.rb
Rails.application.routes.draw do
  root to: 'tours#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get'/about'=> 'about#index'

  resource :cart, only: [:show, :destroy]
  resources :charges

  resources :tours do
    resources :comments
    resources :tour_orders
  end

  resources :accounts do
    resources :orders
  end

  resources :users do
    resources :tours
  end

  resources :tour_orders do
    resources :orders
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :orders, through: :tour_orders
  has_many :tour_orders
  has_many :comments
  belongs_to :user
  validates :price, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }
  has_attached_file :photo, styles: { medium: "300x300>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  #tour filters
  scope :a_z, -> {order(title: :asc)}
  scope :z_a, -> {order(title: :desc)}
  scope :most_recent, -> {order(created_at: :desc)}
  scope :oldest, -> {order(created_at: :asc)}
  scope :most_reviewed, -> { Tour.select("tours.title, tours.description, tours.price, tours.date,tours.photo_file_name, tours.photo_content_type, tours.photo_file_size, tours.id, count(comments.id) as reviews_count")
                            .joins(:comments)
                            .group("tours.id")
                            .order("reviews_count desc")}
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
before_action :authorize_guide_edit, only: [:edit, :update, :destroy]
before_action :authorize_is_guide?, only: [:new,:create]

  def index
    @tours = Tour.all
    if params[:sort] == "a_z"
      @tours = @tours.a_z
    elsif params[:sort] == "z_a"
      @tours = @tours.z_a
    elsif params[:sort] == "most_recent"
      @tours = @tours.most_recent
    elsif params[:sort] == "oldest"
      @tours = @tours.oldest
    elsif params[:sort] == "most_reviewed"
      @tours = @tours.most_reviewed
    end
  end

  def show
    @tour = Tour.find(params[:id])
    @tour_order = current_order.tour_orders.new
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      flash[:notice]= "Tour Created"
      redirect_to tours_path
    else
      render :new
    end
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def update
    @tour = Tour.find(params[:id])
    if @tour.update(tour_params)
      flash[:notice] = "Tour Updated"
      redirect_to "/tours/#{@tour.id}"
    else
      flash[:notice] = "Something went wrong! Check Fields!"
      render :edit
    end
  end

  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    flash[:notice] = "Tour has been removed!"
    redirect_to tours_path
  end

  private

  def tour_params
    params.require(:tour).permit(:user_name, :photo, :title, :price, :description, :location, :date, :time, :user_id, :account_id)
  end
end

app/views/tours/_form.html.erb
<%= render "layouts/errors", :object => @tour %>

<%= form_for @tour do |f| %>
  <%= f.label "What will you call your Tour?" %>
  <%= f.text_field :title, class: "form-control"%>
  <%= f.label "What are you gonna do on your tour?" %>
  <%= f.text_area :description, class: "form-control", rows: 7%>
  <%= f.label "Where will your tour take place?" %>
  <%= f.text_field :location, class: "form-control"%>
  <%= f.label "Date and time it will take place?" %>
  <%= f.date_field :date, min: Date.today, class: "form-control"%>
  <%= f.time_select :time, min: Time.now, ampm: true, default: Time.now, class: "form-control"%>
  <br>
  <%= f.label "What Would You like for Compensation?" %>
  <div class = "input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">$</span>
    </div>
    <%= f.text_field :price, min: 1,  class:"form-control", label: "Amount (to the nearest dollar)"%>
    <div class="input-group-append">
      <span class="input-group-text">.00</span>
    </div>
  </div>
  <!-- <div class="input-group mb-3">
    <div class="custom-file">
      <label class="custom-file-label">Upload Tour Img</label> -->
    <%= f.label "Upload Tour Image"%>
    <%= f.file_field :photo, class: "form-control" %>
    <!--  custom-file-input ^</div>
  </div> -->
  <br>
  <%= f.hidden_field(:user_id, value: current_user.id)%>
  <%= f.submit "Create Tour", class: " btn btn-success form-control"%>
<% end %>

app/views/tours/edit.html.erb
<div class="card guide_tour">
  <div class="card-body">
    <h1>Edit Tour for <%=@tour.title%></h1>
    <%= render "form" %>
  </div>
</div>

app/views/tours/index.html.erb
<div class ="row">
  <div class="col-md-12">
    <div class="dropdown">
      <button class="btn btn-dark dropdown-toggle" id="tour_filter" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Filter Tours By:
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="/" selected >All</a>
        <a class="dropdown-item" href="?sort=a_z">Title: A-Z</a>
        <a class="dropdown-item" href="?sort=z_a">Title: Z-A</a>
        <a class="dropdown-item" href="?sort=most_recent">Most Recent</a>
        <a class="dropdown-item" href="?sort=oldest">Oldest</a>
        <a class="dropdown-item" href="?sort=most_reviewed">Most Reviewed</a>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <% @tours.each do |tour| %>
    <div class = "col-md-4">
      <div class = "card tour_card">
          <div class = "card-body">
          <h1><%= link_to tour.title, tour_path(tour) %></h1>
            <%= link_to image_tag(tour.photo.url(:medium),class:"tour_img"), tour_path(tour)%>
            <p>"<%= tour.description %>"</p>
            <p>Price: <%= number_to_currency tour.price %></p>
            <p>Tour Date: <%= tour.date %></p>
            <% if is_admin? %>
              <%= link_to "Edit", edit_tour_path(tour) %> |
              <%= link_to "Delete", tour_path(tour),
            :data=>{:confirm => "Are You Sure?", :method => "delete"}%>
            <% end %>
          </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/tours/new.html.erb
<div class="card guide_tour">
  <div class="card-body">
    <h1>Create A Tour</h1>
    <%= render "form" %>
  </div>
</div>

app/views/tours/show.html.erb
<div class = "row">
  <div class = "col-md-4 tour_details">
    <div class = "card">
      <div class = "card-body">
        <h1 class="tour_title"><%= @tour.title %></h1>
        <h4 class="price"><%= number_to_currency @tour.price%></h4>
        <%= image_tag @tour.photo.url(:medium), class: "tour_img"%>
        <% if is_guide? && current_user.id == @tour.user_id || is_admin? %>
        <br>
          <p><%= link_to "Edit", edit_tour_path(@tour) %> |
          <%= link_to "Delete", tour_path(@tour),
          :data=>{:confirm => "Are You Sure?", :method => "delete"}%>
        <% end %></p>
        Hosted By: <%= @tour.user.user_name %> <%=image_tag @tour.user.avatar.url(:small),class:"avatar"%>
        <br>
        <br>
        Description: <%= @tour.description%>
        <br>
        <br>
        Location: <%= @tour.location %>
        <br>
        Time: <%=@tour.time.strftime("%I:%M%P")%>
        <%= render "layouts/errors", :object => @tour_order %>
        <%= form_for @tour_order do |f| %>
          <br>
          <%= f.label "Number in Party?(Max 5)"%>
          <%= f.select :quantity,([["1",1],["2",2],["3",3],["4",4],["5",5]]), class:"form-control" %>
          <br>
          <%= f.hidden_field :tour_id, value: @tour.id %>
          <br>
          <%= f.submit "Add to Your Itinerary", class: "btn btn-dark form-control" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4" id="map">
    <div class="card">
      <%= link_to "http://maps.google.com/maps?q=#{@tour.latitude},#{@tour.longitude}", target: :_blank do %>
      <%=image_tag  "http://maps.googleapis.com/maps/api/staticmap?center=#{@tour.latitude},#{@tour.longitude}&markers=#{@tour.latitude},#{@tour.longitude}&zoom=20&size=720x480&key="+ ENV['MAP_KEY'], class: 'img-fluid img-rounded', alt: "#{@tour.title} on the map"%>
     <% end %>
     <p>Click Map For More Details (Opens a New Window)</p>
    </div>
  </div>
  <div class= "col-md-4 comment">
    <% if @tour.comments.any? %>
      <div class= "card">
          <h3 class="addComment">Comments for <%= @tour.title %></h3>
          <% if current_user %>
            <%=link_to "Leave a comment", new_tour_comment_path(@tour), class:"addComment", remote: true%>
          <% end %>
        <div class= "card-body comment_display">
        <% @tour.comments.each do |comment| %>
          <div class="comment_each">
            <%=image_tag comment.user.avatar.url(:small), class:"avatar"%> <em><%= comment.user.user_name %></em>
            -  "<%= comment.body %>"
            <% if current_user && current_user.id === comment.user_id || is_admin? %>
            <p class="comment_tag"><%= link_to "Edit", edit_tour_comment_path(comment) %> |
            <%= link_to "Delete", tour_comment_path(comment),
            :data=>{:confirm => "Delete Comment?", :method => "delete"}%></p>
            <% end %>
          </div>
        <br>
        <hr>
        <% end %>
        <span class= "displayComment commentEdit"></span>
      <% else %>
      <div class = "card comment_display">
        <p class= "addComment">There are currently no comments for this tour.</p>
           <% if current_user %>
           <p class="addComment">Been on this tour? <%= link_to "Let others know what you think about it!", new_tour_comment_path(@tour), remote: true%></p>
           <% end %>
           <span class= "displayComment"></span>
        </div>
    <% end %>
      </div>
    </div>
  </div>
</div>