config/routes.rb
Rails.application.routes.draw do
  root to: 'tours#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get'/about'=> 'about#index'

  resource :cart, only: [:show, :destroy]
  resources :charges

  resources :tours do
    resources :comments
    resources :tour_orders
  end

  resources :accounts do
    resources :orders
  end

  resources :users do
    resources :tours
  end

  resources :tour_orders do
    resources :orders
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authorize_cart, only: [:show]

  def show
    @tour_orders = current_order.tour_orders
  end
end

app/views/carts/show.html.erb
<div class = "card cart_display">
  <div class = "card-body">
    <h3>Current Tours</h3>
    <hr>
    <% if @tour_orders.any? %>
      <% @tour_orders.each do |item| %>
      <p><strong><%= item.tour.title %></strong></p>
      <p>Guide Name: <%= item.tour.user.user_name %></p>
      <p>Number in tour: <%= item.quantity%></p>
      <strong><p>Price: <%= number_to_currency item.tour.price%></p></strong>
      <strong><p class="remove_item"><%= link_to "Remove From Cart", tour_order_path(item),
          :data=>{:confirm => "Remove Tour From Cart?", :method => "delete"}%></p></strong>
      <hr>
      <% end %>
      <h4> Cart Total: <%= number_to_currency current_order.total_price %></h4>
      <br>
    <%= link_to "Checkout", new_charge_path, class: "btn btn-primary" %>      <i class="fa fa-cc-stripe fa-lg" aria-hidden="true"></i>

    <% else %>
      <p><%= "You havent signed up for any tours yet."%> <%= link_to "Go and check'em out!", tours_path %></p>
    <% end %>
  </div>
  <h4 class = "back"><%= link_to "Back To Tours", tours_path %></h4>
</div>