config/routes.rb
Rails.application.routes.draw do
  root to: 'tours#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get'/about'=> 'about#index'

  resource :cart, only: [:show, :destroy]
  resources :charges

  resources :tours do
    resources :comments
    resources :tour_orders
  end

  resources :accounts do
    resources :orders
  end

  resources :users do
    resources :tours
  end

  resources :tour_orders do
    resources :orders
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authorize
  def new
    @amount = current_user.account.orders.last.total_price
    @tour_orders = current_order.tour_orders
  end

  def create
    # Amount in cents
    @amount = current_user.account.orders.last.total_price
    @tour_orders = current_order.tour_orders
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => (@amount * 100).to_i,
      :description => 'Rails Stripe Customer',
      :currency    => 'usd'
    )
    ApplicationMailer.reciept_email(current_user.email,@tour_orders, @amount).deliver_now
    current_order.update(:status => "paid");
    session[:order_id] = nil
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class = "card pay_rec">
  <h2>Thanks For Choosing Urban Sherpa!</h2>
    <img class="jump" src="../thanksImg/wahoo.gif" alt="Thank You! JUMP!JUMP!JUMP!" />
  <h3>Your Tour cost was: <strong><%= number_to_currency @amount %></strong>!</h3>
  <h4><%= link_to "Back To Tours", tours_path %> </h4>
</div>

app/views/charges/new.html.erb
<div class = "card pay">
  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <% @tour_orders.each do |item| %>
        <p><%=item.tour.title %></p>
        <% end %>
        <span><h3>Your Total: </h3> <h5><%= number_to_currency @amount %></h5></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description= "<%= current_user.account.orders.last.tour_orders.last.tour.title %>"
            data-amount= "<%= @amount * 100 %>"
            data-locale="auto"></script>
  <% end %>
  <br>
  <p> <%= link_to "Something Not Look Right? Back To Cart", cart_path%>
</div>