config/routes.rb
Rails.application.routes.draw do
  root to: 'tours#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get'/about'=> 'about#index'

  resource :cart, only: [:show, :destroy]
  resources :charges

  resources :tours do
    resources :comments
    resources :tour_orders
  end

  resources :accounts do
    resources :orders
  end

  resources :users do
    resources :tours
  end

  resources :tour_orders do
    resources :orders
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrbanSherpa</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/c44864b8ea.js"></script>
  </head>
  <header>
  <div class="nav">
  <% if current_user %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <h1 class="navbar-brand">  <i class="fa fa-map" aria-hidden="true"></i>Urban Sherpa</h1>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link"> <%= link_to "Home", tours_path %></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link"> <%= link_to "About", "/about" %></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link"><%= link_to "<i class='fa fa-shopping-cart' aria-hidden='true'></i> Cart: #{tour_cart}".html_safe, cart_path%></a>
        </li>
        <li class="nav-item dropdown" id="user_nav_drop">
          <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="navbarDropdown"><%= current_user.user_name%></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" id="dropmenu_items">
              <%= link_to "/users/#{current_user.id}" do%>
              <div class="dropdown-item"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Profile</div>
              <% end %>
              <div class="dropdown-item">
                <%= link_to cart_path do%>
                <i class="fa fa-sticky-note-o" aria-hidden="true"></i><%= " Itinerary | #{tour_cart}"%>
                <% end %>
              </div>
              <% if is_guide? %>
                <div class="dropdown-item">
                <%= link_to new_tour_path do%>
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                Create Tour
                <% end %>
              <% end %>
                <div class="dropdown-divider"></div>
                <div class="dropdown-item">
                  <%= link_to "/signout" do%>
                    <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>Sign Out
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <% else %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <h1 class="navbar-brand"><i class="fa fa-map" aria-hidden="true"></i>
        <%= link_to "Urban Sherpa", tours_path%></h1>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link"> <%= link_to "About", "/about", class:"btn" %></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link"><%= link_to "Sign Up", "/signup", class: "btn"%></a>
            </li>
          </ul>
          <div class="navbar-nav">
            <a><%= link_to "Sign In", "/signin", remote: true, class:"btn btn-warning navbar-btn signIn_button"%></a>
          </div>
        </div>
      </nav>
    <% end %>
    <span id="dropdown_login"></span>
    <div class = "container">
      <% flash.each do |key, value| %>
        <div class='alert alert-dismissible fade show card alertCard alert_notice' role='alert'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <li aria-hidden="true">&times;</li>
          </button>
          <%= value %>
          <%end%>
        </div>
    </div>
  </div>
  </header>
  <body id="main_body">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/holder.html.erb
<!-- <header>
<div class="nav">
<% if current_user %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h1 class="navbar-brand">Urban Sherpa</h1>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link"> <%= link_to "Home", tours_path %></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link"><%= link_to "Cart: #{tour_cart}", cart_path%></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name%></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><%= link_to "Profile", "/users/#{current_user.id}"%></a>
          <a class="dropdown-item"><%= link_to "Itinerary | #{tour_cart}", cart_path %></a>
          <% if is_guide? %>
          <a class="dropdown-item"><%= link_to "Create A Tour", new_tour_path%></a>
          <% end %>
          <div class="dropdown-divider"></div>
            <a class="dropdown-item"><%= link_to "Sign Out", "/signout"%></a>
        </div>
      </li>
    </ul>
  </div>
</nav>
  <% else %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <h1 class="navbar-brand"><%= link_to "Urban Sherpa", tours_path%></h1>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link"><%= link_to "Sign In", "/signin"%></a>
          <li>
          <li class="nav-item active">
            <a class="nav-link"><%= link_to "Sign Up", "/signup"%></a>
          </li>
        </ul>
      </div>
    </nav>
  <% end %>
</div>
</header> -->